import { normalizeService } from '../normalize-service.js'

/**
 * Internal tool handlers.
 * Each handler receives (params, context) and returns a result string.
 * context = { supabase, userId }
 */

/**
 * save_lead — UPSERT a lead by phone number (enrich if exists, create if new).
 */
async function saveLead(params, { supabase, userId }) {
  const body = params?.body || params || {}

  const { name, phone } = body
  if (!name || !phone) {
    return JSON.stringify({ success: false, error: 'name and phone are required' })
  }

  // Auto-resolve city → branch
  let branch = body.branch || null
  if (!branch && body.city) {
    const { data: idx } = await supabase
      .from('city_branch_index')
      .select('branch_name')
      .eq('user_id', userId)
      .eq('city', body.city)
      .limit(1)
    if (idx?.length) branch = idx[0].branch_name
  }

  // Check if lead already exists by phone + user_id
  const { data: existing } = await supabase
    .from('leads')
    .select('id, name, phone, city, branch, status, service_requested, service_type, details')
    .eq('user_id', userId)
    .eq('phone', phone)
    .order('created_at', { ascending: false })
    .limit(1)

  if (existing?.length) {
    // Enrich existing lead — only update fields that are newly provided and currently empty
    const lead = existing[0]
    const updates = { updated_at: new Date().toISOString() }
    if (name && !lead.name) updates.name = name
    if (body.email) updates.email = body.email
    if (body.city && !lead.city) updates.city = body.city
    if (branch && !lead.branch) updates.branch = branch
    if (body.service_requested && !lead.service_requested) updates.service_requested = normalizeService(body.service_requested)
    if (body.service_type && !lead.service_type) updates.service_type = body.service_type
    if (body.details) updates.details = lead.details ? `${lead.details}\n---\n${body.details}` : body.details

    const { data, error } = await supabase
      .from('leads')
      .update(updates)
      .eq('id', lead.id)
      .select('id, name, phone, city, branch, status')
      .single()

    if (error) {
      console.error('[internal-tools/save_lead]', error.message)
      return JSON.stringify({ success: false, error: error.message })
    }
    return JSON.stringify({ success: true, lead_id: data.id, updated: true, message: `Lead enriched: ${data.name} (${data.phone})` })
  }

  // Create new lead
  const insert = {
    user_id: userId,
    company: body.company || 'babait',
    type: body.type || 'patient',
    name,
    phone,
    email: body.email || null,
    city: body.city || null,
    branch,
    coordinator: body.coordinator || null,
    source: body.source || 'chatbot',
    lead_channel: body.lead_channel || 'whatsapp',
    service_requested: normalizeService(body.service_requested),
    service_type: body.service_type || null,
    details: body.details || null,
    status: 'new',
    position_type: body.position_type || null,
    experience: body.experience ?? null,
    campaign: body.campaign || null,
    custom_fields: body.custom_fields || {},
  }

  const { data, error } = await supabase
    .from('leads')
    .insert(insert)
    .select('id, name, phone, city, branch, status')
    .single()

  if (error) {
    console.error('[internal-tools/save_lead]', error.message)
    return JSON.stringify({ success: false, error: error.message })
  }

  return JSON.stringify({ success: true, lead_id: data.id, message: `Lead saved: ${data.name} (${data.phone})` })
}

/**
 * list_branches — List all active branches for the user.
 */
async function listBranches(params, { supabase, userId }) {
  const { data, error } = await supabase
    .from('branches')
    .select('id, name, address, phone, mobile, contact_name, is_active')
    .eq('user_id', userId)
    .eq('is_active', true)
    .order('name')

  if (error) {
    console.error('[internal-tools/list_branches]', error.message)
    return JSON.stringify({ success: false, error: error.message })
  }

  if (!data || data.length === 0) {
    return JSON.stringify({ success: true, branches: [], message: 'No branches found' })
  }

  const branches = data.map(b => ({
    name: b.name,
    address: b.address || null,
    phone: b.phone || b.mobile || null,
    contact: b.contact_name || null,
  }))

  return JSON.stringify({ success: true, branches, count: branches.length })
}

// --- Handler registry ---

const HANDLERS = {
  save_lead: saveLead,
  list_branches: listBranches,
}

/**
 * Execute an internal tool handler.
 * @param {string} handler - Handler name (e.g., 'save_lead')
 * @param {Object} params - Parameters generated by the LLM
 * @param {Object} context - { supabase, userId }
 * @returns {Promise<string>} Result string
 */
export async function executeInternalTool(handler, params, context) {
  const fn = HANDLERS[handler]
  if (!fn) {
    return `Internal tool error: unknown handler "${handler}"`
  }

  try {
    return await fn(params, context)
  } catch (err) {
    console.error(`[internal-tools/${handler}]`, err.message)
    return `Internal tool error: ${err.message}`
  }
}
