/**
 * Internal tool handlers.
 * Each handler receives (params, context) and returns a result string.
 * context = { supabase, userId }
 */

/**
 * save_lead — Insert a lead into the leads table.
 */
async function saveLead(params, { supabase, userId }) {
  const body = params?.body || params || {}

  const { name, phone } = body
  if (!name || !phone) {
    return JSON.stringify({ success: false, error: 'name and phone are required' })
  }

  // Auto-resolve city → branch
  let branch = body.branch || null
  if (!branch && body.city) {
    const { data: idx } = await supabase
      .from('city_branch_index')
      .select('branch_name')
      .eq('user_id', userId)
      .eq('city', body.city)
      .limit(1)
    if (idx?.length) branch = idx[0].branch_name
  }

  const insert = {
    user_id: userId,
    company: body.company || 'babait',
    type: body.type || 'patient',
    name,
    phone,
    email: body.email || null,
    city: body.city || null,
    branch,
    coordinator: body.coordinator || null,
    source: body.source || 'chatbot',
    lead_channel: body.lead_channel || 'whatsapp',
    service_requested: body.service_requested || null,
    service_type: body.service_type || null,
    details: body.details || null,
    status: 'new',
    position_type: body.position_type || null,
    experience: body.experience ?? null,
    campaign: body.campaign || null,
    custom_fields: body.custom_fields || {},
  }

  const { data, error } = await supabase
    .from('leads')
    .insert(insert)
    .select('id, name, phone, city, branch, status')
    .single()

  if (error) {
    console.error('[internal-tools/save_lead]', error.message)
    return JSON.stringify({ success: false, error: error.message })
  }

  return JSON.stringify({ success: true, lead_id: data.id, message: `Lead saved: ${data.name} (${data.phone})` })
}

// --- Handler registry ---

const HANDLERS = {
  save_lead: saveLead,
}

/**
 * Execute an internal tool handler.
 * @param {string} handler - Handler name (e.g., 'save_lead')
 * @param {Object} params - Parameters generated by the LLM
 * @param {Object} context - { supabase, userId }
 * @returns {Promise<string>} Result string
 */
export async function executeInternalTool(handler, params, context) {
  const fn = HANDLERS[handler]
  if (!fn) {
    return `Internal tool error: unknown handler "${handler}"`
  }

  try {
    return await fn(params, context)
  } catch (err) {
    console.error(`[internal-tools/${handler}]`, err.message)
    return `Internal tool error: ${err.message}`
  }
}
