/**
 * Dynamic tool execution.
 * Executes HTTP API calls defined in the `tools` table,
 * with body generated by the LLM via function calling.
 */

/**
 * Build a tool definition for function calling from a DB tool row.
 * @param {Object} tool - Tool row from the `tools` table
 * @returns {Object} Tool definition compatible with LLM function calling
 */
export function buildToolDef(tool) {
  // Build parameters schema from body_schema
  let parametersSchema = { type: 'object', properties: {} }

  if (tool.body_schema) {
    try {
      const schema = typeof tool.body_schema === 'string'
        ? JSON.parse(tool.body_schema)
        : tool.body_schema
      parametersSchema = {
        type: 'object',
        properties: {
          body: {
            type: 'object',
            description: `Generate JSON matching this schema: ${JSON.stringify(schema)}`,
            properties: schema.properties || schema,
          },
        },
      }
    } catch {
      // If body_schema is not parseable, use empty
    }
  }

  return {
    name: `api_tool_${tool.id}`,
    description: tool.description || `Call the ${tool.name} API`,
    parameters: parametersSchema,
  }
}

// Private/internal IP ranges to block (SSRF protection)
const BLOCKED_IP_RANGES = [
  /^127\./, /^10\./, /^172\.(1[6-9]|2\d|3[01])\./, /^192\.168\./,
  /^0\./, /^169\.254\./, /^::1$/, /^fc00:/, /^fe80:/,
  /^localhost$/i,
]

const ALLOWED_SCHEMES = ['http:', 'https:']
const TOOL_TIMEOUT_MS = 30_000

function isUrlSafe(urlString) {
  try {
    const parsed = new URL(urlString)
    if (!ALLOWED_SCHEMES.includes(parsed.protocol)) return false
    const hostname = parsed.hostname
    if (BLOCKED_IP_RANGES.some(re => re.test(hostname))) return false
    return true
  } catch {
    return false
  }
}

/**
 * Execute a dynamic tool call (HTTP request).
 * Includes SSRF protection and timeout.
 * @param {Object} tool - Tool row from the `tools` table
 * @param {Object} params - Parameters generated by the LLM
 * @returns {Promise<string>} Response body as string
 */
export async function executeTool(tool, params) {
  const method = (tool.method || 'GET').toUpperCase()
  let url = tool.url

  // SSRF protection: validate URL
  if (!isUrlSafe(url)) {
    return `Tool error: URL blocked by security policy`
  }

  // Apply query parameters
  if (tool.query_parameters) {
    const qp = typeof tool.query_parameters === 'string'
      ? JSON.parse(tool.query_parameters)
      : tool.query_parameters
    const searchParams = new URLSearchParams()
    for (const [key, value] of Object.entries(qp)) {
      if (value !== null && value !== undefined) {
        searchParams.append(key, value)
      }
    }
    const qs = searchParams.toString()
    if (qs) url += (url.includes('?') ? '&' : '?') + qs
  }

  // Build headers
  const headers = { 'Content-Type': 'application/json' }
  if (tool.headers) {
    const h = typeof tool.headers === 'string' ? JSON.parse(tool.headers) : tool.headers
    Object.assign(headers, h)
  }

  // Build fetch options with timeout
  const controller = new AbortController()
  const timeout = setTimeout(() => controller.abort(), TOOL_TIMEOUT_MS)
  const fetchOpts = { method, headers, signal: controller.signal }

  // Add body for non-GET requests
  if (method !== 'GET' && method !== 'HEAD') {
    const body = params?.body || params || {}
    fetchOpts.body = JSON.stringify(body)
  }

  try {
    const response = await fetch(url, fetchOpts)
    clearTimeout(timeout)
    const text = await response.text()

    if (!response.ok) {
      return `API Error (${response.status}): ${text.slice(0, 500)}`
    }

    // Try to parse JSON for cleaner output
    try {
      const json = JSON.parse(text)
      return JSON.stringify(json, null, 2).slice(0, 2000)
    } catch {
      return text.slice(0, 2000)
    }
  } catch (err) {
    clearTimeout(timeout)
    if (err.name === 'AbortError') {
      return `Tool error: request timed out after ${TOOL_TIMEOUT_MS / 1000}s`
    }
    return `Tool execution error: ${err.message}`
  }
}
